name: spotify_plus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3

  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  logger: ^1.0.0

  http: ^0.13.3
  spotify: ^0.6.0
  oauth2: ^2.0.0
  url_launcher: ^6.0.9

  equatable: ^2.0.3

  provider: ^5.0.0
  flutter_bloc: ^7.1.0
  get_it: ^7.2.0
  injectable: 1.4.1

  vrouter: ^1.2.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  build_runner: ^2.0.6
  json_serializable: any
  freezed: ^0.14.1+3
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
